### ISSUE TITLE
Some `consul.Client` urls have a double '/' leading URL

### ISSUE THREAD

**Issue by giupo** [javicacheiro/consul-service-discovery#2]
`consul.Client().url_register` yields the expected `'http://localhost:8500/v1/agent/service/register'`, which is correct.

but `consul.Client().url_serives` yields `'http://localhost:8500//v1/catalog/services'` which creates an unecessary 304 HTTP response from consul.

**Comment by javicacheiro** [comment]
Thanks for the fix!
